<Project>

  <PropertyGroup>

    <!-- Framework mínimo requerido -->
    <MinimumNetVersion>10.0</MinimumNetVersion>

    <!-- Framework por defecto -->
    <TargetFramework>net10.0</TargetFramework>

    <!-- Calidad de código -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Tratar warnings como errores -->
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Análisis de código -->
    <AnalysisLevel>latest</AnalysisLevel>

  </PropertyGroup>

</Project>